[package]
name = "pico_chess"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.3.1"
const-random = "0.1.18"
strum = { version = "0.27.1", features = ["derive"] }

[dev-dependencies]
enum-iterator = "1.4.1"
