[package]
name = "pico_chess_proc_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
const-random = "0.1.18"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
