[package]
name = "position"
version = "0.1.0"
edition = "2021"

[dependencies]
board = { path = "../board" }

bitflags = "2.3.1"
strum = { version = "0.27.1", features = ["derive"] }
const-random = "0.1.18"
