[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
position = { path = "../position" }
board = { path = "../board" }
multithreading = { path = "../multithreading" }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel", "crossbeam-deque"] }
