[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
game = { path = "../game" }
multithreading = { path = "../multithreading" }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel", "crossbeam-deque"] }
